export const CONFIG = {
    REAL_HOURS_PER_GAME_DAY: 6,
    GAME_MINUTES_PER_REAL_MINUTE: (24 / 6),
    DEFAULT_ROUND_START_DATE: new Date(2025, 6, 2, 12, 0),
    ROUND_DURATION_GAME_DAYS: 52,
    CLASS_IDS: ['assassino', 'cafetao', 'corretor', 'empresario', 'ladrao', 'traficante'],
    ATTRIBUTES_IDS: ['forca', 'tolerancia', 'inteligencia', 'carisma']
};

export const i18n = {
    en: {
        title: "The Crims Calculator",
        subtitle: "Tools to optimize your game.",
        timeCalcTab: "Time Calculator",
        pointsCalcTab: "Points Calculator",
        calculate: "Calculate",
        reset: "Reset",
        day: "Day",
        hour: "Hour",
        minute: "Minute",
        roundStartLabel: "Round Start (Real Time):",
        roundEndLabel: "Round End (Real Time):",
        currentGameTime: "Current Game Time",
        desiredGameTime: "Desired Game Time",
        realTimeNeeded: "Real time needed",
        localTimePrefix: "Predicted local time",
        errorInvalidStart: "Please enter a valid Round Start Date/Time in the past.",
        errorFillFields: "Please fill all 'Desired Time' fields.",
        errorFutureTime: "Desired time must be in the future.",
        timeIsSame: "Current and desired time are the same.",
        and: "and",
        hour_one: "hour",
        hour_other: "hours",
        minute_one: "minute",
        minute_other: "minutes",
        totalPointsLabel: "Total Points:",
        loadClassPreset: "Load Class Preset:",
        copyBuild: "Copy Build",
        resetPreset: "Reset Preset",
        copied: "Copied!",
        buildWith: "Build with",
        points: "points",
        totalPercent: "Total %",
        errorInvalidPoints: "Please enter a valid number of points.",
        errorPercentSum: "The sum of percentages must be 100%.",
        assassino: "Hitman",
        cafetao: "Pimp",
        corretor: "Broker",
        empresario: "Businessman",
        ladrao: "Robber",
        traficante: "Dealer",
        forca: "Strength",
        tolerancia: "Tolerance",
        inteligencia: "Intelligence",
        carisma: "Charisma",
        footerText: `Developed with 🧠 by <a href="https://github.com/bernardotraad" target="_blank" class="font-semibold text-amber-400 hover:underline">Bernardo Traad</a>`
    },
    pt: {
        title: "Calculadora The Crims",
        subtitle: "Ferramentas para otimizar seu jogo.",
        timeCalcTab: "Calculadora de Tempo",
        pointsCalcTab: "Calculadora de Pontos",
        calculate: "Calcular",
        reset: "Redefinir",
        day: "Dia",
        hour: "Hora",
        minute: "Minuto",
        roundStartLabel: "Início da Rodada (Real):",
        roundEndLabel: "Fim da Rodada (Real):",
        currentGameTime: "Tempo Atual no Jogo",
        desiredGameTime: "Tempo Desejado no Jogo",
        realTimeNeeded: "Tempo real necessário",
        localTimePrefix: "Hora local prevista",
        errorInvalidStart: "Por favor, insira uma Data/Hora de Início da Rodada válida e no passado.",
        errorFillFields: "Por favor, preencha todos os campos de 'Tempo Desejado'.",
        errorFutureTime: "O tempo desejado deve ser no futuro.",
        timeIsSame: "O tempo atual e o desejado são os mesmos.",
        and: "e",
        hour_one: "hora",
        hour_other: "horas",
        minute_one: "minuto",
        minute_other: "minutos",
        totalPointsLabel: "Total de Pontos:",
        loadClassPreset: "Carregar Padrão da Classe:",
        copyBuild: "Copiar Build",
        resetPreset: "Redefinir Padrão",
        copied: "Copiado!",
        buildWith: "Build com",
        points: "pontos",
        totalPercent: "Total %",
        errorInvalidPoints: "Por favor, insira um total de pontos válido.",
        errorPercentSum: "A soma das porcentagens deve ser 100%.",
        assassino: "Assassino de Aluguel",
        cafetao: "Cafetão",
        corretor: "Corretor",
        empresario: "Empresário",
        ladrao: "Ladrão",
        traficante: "Traficante",
        forca: "Força",
        tolerancia: "Resistência",
        inteligencia: "Inteligência",
        carisma: "Carisma",
        footerText: `Desenvolvido com 🧠 por <a href="https://github.com/bernardotraad" target="_blank" class="font-semibold text-amber-400 hover:underline">Bernardo Traad</a>`
    }
};

export const CLASS_DISTRIBUTIONS = {
    assassino: { forca: 0.50, tolerancia: 0.30, inteligencia: 0.15, carisma: 0.05 },
    cafetao: { carisma: 0.40, inteligencia: 0.25, tolerancia: 0.25, forca: 0.10 },
    corretor: { inteligencia: 0.45, carisma: 0.35, tolerancia: 0.15, forca: 0.05 },
    empresario: { inteligencia: 0.45, carisma: 0.35, tolerancia: 0.15, forca: 0.05 },
    ladrao: { inteligencia: 0.40, tolerancia: 0.35, forca: 0.20, carisma: 0.05 },
    traficante: { inteligencia: 0.38, tolerancia: 0.28, carisma: 0.28, forca: 0.06 }
};